local defarc = require "defarc.defarc"
local defarc_test = require "defarc.defarc_test"	-- unit and functional testing, not needed for project

local options = {}									-- store current options table locally for convenience in input handling

function show_current_text_and_options()			-- helper function to get and set current dialogue text and options
	local text = defarc.get_text()
	options = defarc.get_options_table()

	gui.set_text(gui.get_node("NPC"), text)			-- set text

	for i=1,3 do									-- set 3 corresponding options - can be improved with a dynamic list
		local option_node = gui.get_node("Option_"..i)
		local option_text = options[i] and options[i].label or ""
		gui.set_text(option_node, option_text)
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	defarc_test.run()									-- unit and functional testing, not needed for project

	defarc.load("/examples/dialogs/test_board/test_board.json")	-- loading Arcweave exported JSON from custom resources
	local start_id = defarc.get_starting_element_id()	-- get starting element id
	defarc.select_element_by_id(start_id)				-- select element by its id

	show_current_text_and_options()						-- display text and options from selected element
end

function on_input(self, action_id, action)
	for i = 1,3 do
		local current_option_node = gui.get_node("Option_"..i)

		if gui.pick_node(current_option_node, action.x, action.y) then	-- handle clicking on option nodes
			if action.pressed then
				gui.set_scale(current_option_node, vmath.vector4(0.9))	-- scale clicked options a little
			elseif action.released then
				gui.set_scale(current_option_node, vmath.vector4(1))	-- scale it back when released

				defarc.select_element(options[i].target_id)				-- select next element

				if defarc.get_element_title() == "Exit" then			-- if one of elements have title "Exit"
					local start_id = defarc.get_starting_element_id()	-- we will just start over (or we can quit the conversation here)
					defarc.select_element_by_id(start_id)
				end

				show_current_text_and_options()							-- display next text and options
			end
			return true
		end
	end
end

function final(self)
	msg.post(".", "release_input_focus")
end